services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: demo_api
    restart: always
    ports:
      - "4000:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DATABASE_URL="testDb"
